name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src

  build-ubuntu:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
  
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src

  test-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Tests

    - name: Test
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: ./src/Tests

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: src/Tests/coverage/**/coverage.cobertura.xml
        format: text
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: console